[workspace]
resolver = "2"

members = [
    "crates/ltk_game_data",
    "crates/ltk_game_index",
    "crates/league-mod",
    "crates/ltk_fantome",
    "crates/ltk_hashtable",
    "crates/ltk_mod_core",
    "crates/ltk_modpkg",
    "crates/ltk_mod_project",
    "crates/ltk_overlay",
]

[workspace.dependencies]
# LeagueToolkit crates
ltk_hash = "0.4"
ltk_primitives = "0.3"
glam = "0.27"
ltk_wad = "0.5.4"
ltk_file = "0.2.11"
ltk_meta = "0.8.5"
ltk_io_ext = "0.4.4"
ltk_rst = "0.2.0"

# Workspace crates
ltk_fantome = { version = "0.13.0", path = "crates/ltk_fantome" }
ltk_game_data = { version = "0.3.0", path = "crates/ltk_game_data" }
ltk_game_index = { version = "0.1.1", path = "crates/ltk_game_index" }
ltk_hashtable = { version = "0.1.3", path = "crates/ltk_hashtable" }
ltk_mod_core = { version = "0.1.1", path = "crates/ltk_mod_core" }
ltk_mod_project = { version = "0.11.0", path = "crates/ltk_mod_project" }
ltk_modpkg = { version = "0.11.0", path = "crates/ltk_modpkg" }

# Shared
binrw = "0.14.1"
byteorder = "1.5"
camino = "1.1"
image = { version = "0.25", default-features = false }
indexmap = { version = "2", features = ["serde"] }
rayon = "1.10"
rmp-serde = "1.3"
semver = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slug = "0.1"
sysinfo = "0.32"
tempfile = "3.15"
thiserror = "2"
toml = "1.1"
tracing = "0.1"
walkdir = "2"
xxhash-rust = { version = "0.8", features = ["xxh3", "xxh64"] }
zip = "2.4"
zstd = "0.13"
