[workspace]
resolver = "2"

members = [
    "crates/league-mod",
    "crates/ltk_fantome",
    "crates/ltk_hashtable",
    "crates/ltk_mod_core",
    "crates/ltk_modpkg",
    "crates/ltk_mod_project",
    "crates/ltk_overlay",
]

[workspace.dependencies]
camino = "1.1"
indexmap = { version = "2", features = ["serde"] }
ltk_hash = "0.4"
ltk_wad = "0.5.4"
sysinfo = "0.32"
