# cargo-deny configuration
# See https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "all"
yanked = "warn"
notice = "warn"
ignore = [
    # Add any specific advisories you want to ignore here
]

[advisories.severity]
unmaintained = "warn"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "AGPL-3.0",
]
deny = ["GPL-2.0", "GPL-3.0", "LGPL-2.1", "LGPL-3.0"]
confidence-threshold = 0.8
exceptions = [
    # Allow specific packages with different licenses if needed
]

[bans]
deny = [
    # Add any crates you want to ban here
]
skip = [
    # Add crates that are okay to have multiple versions
]
skip-tree = [
    # Skip dependency trees
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
