# cargo-deny configuration
# See https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
]

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "workspace"
yanked = "warn"
ignore = [
    # Add any specific advisories you want to ignore here
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSL-1.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "AGPL-3.0-only",
    "Unicode-3.0",
    "MPL-2.0",
    "ISC",
]
confidence-threshold = 0.8
clarify = [
    # External unlicensed crates from league-toolkit - assign AGPL-3.0-only license
    { name = "io-ext", version = "*", expression = "AGPL-3.0-only", license-files = [
    ] },
    { name = "league-primitives", version = "*", expression = "AGPL-3.0-only", license-files = [
    ] },
]
exceptions = [
    # Allow specific packages with different licenses if needed
]

[bans]
deny = [
    # Add any crates you want to ban here
]
skip = [
    # Add crates that are okay to have multiple versions
]
skip-tree = [
    # Skip dependency trees
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/LeagueToolkit/league-toolkit.git"]
