# Locale manifest for league-mod
PackageIdentifier: LeagueToolkit.LeagueMod
PackageVersion: 0.1.0
PackageLocale: en-US
Publisher: LeagueToolkit
PublisherUrl: https://github.com/LeagueToolkit/league-mod
PublisherSupportUrl: https://github.com/LeagueToolkit/league-mod/issues
# PrivacyUrl:
Author: LeagueToolkit
PackageName: League Mod
PackageUrl: https://github.com/LeagueToolkit/league-mod
License: AGPL-3.0
LicenseUrl: https://github.com/LeagueToolkit/league-mod/blob/main/LICENSE
# Copyright:
# CopyrightUrl:
ShortDescription: A comprehensive toolkit for creating, managing, and distributing League of Legends mods
Description: |-
  League Mod is a powerful command-line toolkit for League of Legends mod developers and users. 
  It provides a complete solution for creating, managing, and distributing mods using the modpkg format.

  Key features:
  • Initialize new mod projects with interactive prompts
  • Pack mod projects into distributable .modpkg files
  • Extract existing .modpkg files for inspection or modification
  • Display detailed information about mod packages
  • Layer-based mod organization with priority system
  • Support for file transformers and preprocessing
  • Cross-format configuration (JSON and TOML)

  Perfect for both mod creators who want to package and distribute their work, and end users who want to manage and install League of Legends mods easily.
# Moniker:
Tags:
  - league-of-legends
  - modding
  - gaming
  - cli
  - toolkit
  - lol
  - mods
  - package-manager
# Agreements:
ReleaseNotes: |-
  Initial release of League Mod toolkit.

  Features included:
  • Project initialization and management
  • Mod packaging and extraction
  • Layer system for modular mods
  • Rich metadata support
  • File transformation system
ReleaseNotesUrl: https://github.com/LeagueToolkit/league-mod/releases/tag/v0.1.0
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.6.0
