[package]
name = "ltk_fantome"
version = "0.12.0"
edition = "2024"
license = "Apache-2.0"
description = "Helper library for working with League of Legends mods in the legacy Fantome format"
repository = "https://github.com/LeagueToolkit/league-mod"
homepage = "https://github.com/LeagueToolkit/league-mod"
documentation = "https://github.com/LeagueToolkit/league-mod/wiki"
readme = "../../README.md"
keywords = ["league-of-legends", "modding", "gaming", "toolkit"]
categories = ["game-development"]
authors = ["LeagueToolkit"]

[dependencies]
ltk_game_data = { workspace = true }
indexmap = { workspace = true }
zip = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }
camino = { workspace = true }
tempfile = { workspace = true }
zstd = { workspace = true }
ltk_wad = { workspace = true }
ltk_file = { workspace = true }
ltk_hashtable = { workspace = true }

[dev-dependencies]
ltk_hash = { workspace = true }
xxhash-rust = { workspace = true }
