[package]
name = "ltk_modpkg"
version = "0.12.3"
edition = "2021"
license = "Apache-2.0"
description = "League Toolkit mod package (.modpkg) reader/writer and utilities"
repository = "https://github.com/LeagueToolkit/league-mod"
homepage = "https://github.com/LeagueToolkit/league-mod"
documentation = "https://github.com/LeagueToolkit/league-mod/wiki"
readme = "README.md"
keywords = ["league-of-legends", "modding", "gaming", "toolkit"]
categories = ["game-development"]
authors = ["LeagueToolkit"]

[dependencies]
ltk_game_data = { workspace = true }
indexmap = { workspace = true }
thiserror = { workspace = true }
byteorder = { workspace = true }
ltk_io_ext = { workspace = true }
ltk_hashtable = { workspace = true }
serde = { workspace = true }
rmp-serde = { workspace = true }
binrw = { workspace = true }
itertools = "0.14.0"
zstd = { workspace = true }
semver = { workspace = true, features = ["serde"] }
xxhash-rust = { workspace = true }

[dev-dependencies]
proptest = "1.6.0"
proptest-derive = "0.5.1"
tempfile = { workspace = true }
