name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build release binary
        run: cargo build --release --bin league-mod

      - name: Get version from tag
        id: get_version
        shell: powershell
        run: |
          if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
            $version = "${{ github.event.inputs.tag }}"
          } else {
            $version = $env:GITHUB_REF -replace 'refs/tags/', ''
          }
          $version_number = $version -replace '^v', ''
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "version_number=$version_number" >> $env:GITHUB_OUTPUT

      - name: Create release directory
        run: |
          mkdir release
          Copy-Item target/release/league-mod.exe release/
          Copy-Item README.md release/
          Copy-Item LICENSE release/

      - name: Create ZIP archive
        shell: powershell
        run: |
          $version = "${{ steps.get_version.outputs.version_number }}"
          Compress-Archive -Path release/* -DestinationPath "league-mod-$version-windows-x64.zip"

      - name: Generate SHA256 checksum
        shell: powershell
        run: |
          $version = "${{ steps.get_version.outputs.version_number }}"
          $hash = Get-FileHash "league-mod-$version-windows-x64.zip" -Algorithm SHA256
          $hash.Hash | Out-File "league-mod-$version-windows-x64.zip.sha256" -Encoding ASCII
          echo "SHA256: $($hash.Hash)"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            league-mod-${{ steps.get_version.outputs.version_number }}-windows-x64.zip
            league-mod-${{ steps.get_version.outputs.version_number }}-windows-x64.zip.sha256
          body: |
            ## Changes in ${{ steps.get_version.outputs.version }}

            ### Installation via winget
            ```
            winget install LeagueToolkit.LeagueMod
            ```

            ### Manual Installation
            1. Download the ZIP file below
            2. Extract to your desired location
            3. Add the extracted directory to your PATH

            ### SHA256 Checksum
            Verify the integrity of your download:
            ```
            Get-FileHash league-mod-${{ steps.get_version.outputs.version_number }}-windows-x64.zip -Algorithm SHA256
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
